import getpass
import os
import re
import sys
from pathlib import Path

ENV_PATH = Path(__file__).resolve().parent.parent / ".env"
EXAMPLE_PATH = Path(__file__).resolve().parent.parent / ".env.example"


def _prompt(msg: str, default: str = "", secret: bool = False) -> str:
    if secret and default:
        # Never echo an existing secret back to the terminal
        label = f"{msg} [press Enter to keep existing]: "
    else:
        label = f"{msg} [{default}]: " if default else f"{msg}: "
    try:
        if secret:
            try:
                val = getpass.getpass(label).strip()
            except (EOFError, OSError, Exception):
                # No TTY (piped stdin, CI) — fall back to visible input
                val = input(label).strip()
        else:
            val = input(label).strip()
    except (EOFError, KeyboardInterrupt):
        print("\nSetup cancelled.")
        sys.exit(1)
    return val or default


def _valid_token(tok: str) -> bool:
    return bool(re.fullmatch(r"\d{6,}:[\w-]{20,}", tok.strip())) and len(tok.strip()) <= 120


def _valid_db_url(url: str) -> bool:
    u = url.strip()
    return u.startswith(("sqlite+aiosqlite://", "sqlite://",
                         "postgresql+asyncpg://", "postgresql://", "postgres://"))


def _valid_ids(raw: str) -> bool:
    if not raw.strip():
        return True
    try:
        [int(x.strip()) for x in raw.strip().strip("[]() ").split(",") if x.strip()]
        return True
    except ValueError:
        return False


def _read_existing() -> dict:
    vals: dict = {}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                vals[k.strip()] = v.strip()
    return vals


def main() -> None:
    print("🧙 Aegis setup — writes a local .env (never commit it).")
    print(f"Target: {ENV_PATH}\n")
    existing = _read_existing()
    if existing:
        print("Found existing .env values — press Enter to keep them.\n")

    while True:
        tok = _prompt("Bot token from @BotFather",
                      default=existing.get("BOT_TOKEN", ""), secret=True)
        if _valid_token(tok):
            break
        print("❌ That doesn't look like a bot token (expected 123…:ABC…). Try again.")

    while True:
        url = _prompt("Database URL",
                      default=existing.get("DATABASE_URL", "sqlite+aiosqlite:///./aegis.db"))
        if _valid_db_url(url):
            break
        print("❌ URL must start with sqlite+aiosqlite:// or postgresql+asyncpg://")

    level = _prompt("Log level (DEBUG/INFO/WARNING/ERROR)",
                    default=existing.get("LOG_LEVEL", "INFO")).upper() or "INFO"
    if level not in ("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"):
        print("⚠️ Unknown level, using INFO.")
        level = "INFO"

    while True:
        ids = _prompt("Super admin Telegram user IDs (comma-separated, Enter to skip)",
                      default=existing.get("SUPER_ADMIN_IDS", ""))
        if _valid_ids(ids):
            break
        print("❌ Must be numbers like 111,222.")

    name = _prompt("Bot display name", default=existing.get("BOT_NAME", "Aegis")) or "Aegis"

    warn_action = _prompt("Action on warn-limit (mute/ban/kick)",
                          default=existing.get("WARN_ACTION", "mute")).lower() or "mute"
    if warn_action not in ("mute", "ban", "kick"):
        print("⚠️ Unknown action, using mute.")
        warn_action = "mute"

    ENV_PATH.write_text(
        "# Generated by `python -m app.setup`. DO NOT COMMIT.\n"
        f"BOT_TOKEN={tok.strip()}\n"
        f"DATABASE_URL={url.strip()}\n"
        f"LOG_LEVEL={level}\n"
        f"SUPER_ADMIN_IDS={ids.strip()}\n"
        f"BOT_NAME={name.strip()}\n"
        f"WARN_ACTION={warn_action}\n",
        encoding="utf-8",
    )
    try:
        os.chmod(ENV_PATH, 0o600)
    except OSError:
        pass
    print(f"\n✅ Wrote {ENV_PATH} (mode 600).")
    print("Next: .venv/bin/python -m app.main")


if __name__ == "__main__":
    main()
