#!/usr/bin/env node
/**
 * build-legal.mjs — render the repository's legal documents into the landing.
 *
 * PRIVACY.md and TERMS.md at the repo root are the single source of truth.
 * This script renders them with `marked` and writes landing/privacy.html and
 * landing/terms.html, so the site can never drift from the repository: edit the
 * markdown, run `npm run dev` (or `npm run build`) and the pages follow.
 *
 * Deploy builds (e.g. Anybuild) only receive the landing/ directory, so the
 * script falls back to the vendored copies in landing/legal/ when the repo
 * root files are not present in the build context.
 *
 * Output is deterministic — no build timestamp — so regenerating unchanged
 * documents produces no diff.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

import { marked } from 'marked';

const here = dirname(fileURLToPath(import.meta.url));
const landing = join(here, '..');
const repo = join(landing, '..');

const REPO_URL = 'https://github.com/mrsehajofficial/aegis/blob/main';

// Deploy environments (e.g. Anybuild) build from landing/ alone, so the parent
// directory does not exist there. Canonical copies live at the repo root during
// local development; landing/legal/ holds vendored copies for deployments.
const DOC_SEARCH_PATHS = [repo, landing, join(landing, 'legal')];

const PAGES = [
  {
    fileName: 'PRIVACY.md',
    out: join(landing, 'privacy.html'),
    title: 'Privacy Policy',
    badge: 'PRIVACY // DATA HANDLING',
    slug: 'privacy.html',
    description:
      "How the Aegis Telegram bot handles data: what is stored, what never leaves the operator's host, and how to have data deleted.",
  },
  {
    fileName: 'TERMS.md',
    out: join(landing, 'terms.html'),
    title: 'Terms of Service',
    badge: 'TERMS // ACCEPTABLE USE',
    slug: 'terms.html',
    description:
      'The terms that apply to the Aegis Telegram bot: acceptable use, admin responsibilities, availability and liability.',
  },
];

async function resolveSource(fileName) {
  for (const dir of DOC_SEARCH_PATHS) {
    const candidate = join(dir, fileName);
    try {
      return { source: candidate, markdown: await readFile(candidate, 'utf8') };
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
  }
  throw new Error(
    `build-legal: could not find ${fileName} in any of:\n` +
      DOC_SEARCH_PATHS.map((dir) => `  - ${join(dir, fileName)}`).join('\n')
  );
}

const template = await readFile(join(landing, 'legal.template.html'), 'utf8');

for (const page of PAGES) {
  const { markdown } = await resolveSource(page.fileName);
  const content = await marked.parse(markdown, { gfm: true });
  const sourceFile = page.fileName;

  const html = template
    .replaceAll('{{TITLE}}', page.title)
    .replaceAll('{{BADGE}}', page.badge)
    .replaceAll('{{DESCRIPTION}}', page.description)
    .replaceAll('{{SLUG}}', page.slug)
    .replaceAll('{{CONTENT}}', content)
    .replaceAll('{{SOURCE_FILE}}', sourceFile)
    .replaceAll('{{SOURCE_URL}}', `${REPO_URL}/${sourceFile}`)
    .replace(
      '<!-- generated -->',
      `<!-- GENERATED by scripts/build-legal.mjs from ${sourceFile}.\n` +
        '     Edit the markdown at the repository root, never this file. -->'
    );

  await writeFile(page.out, html, 'utf8');
  console.log(`legal: ${sourceFile} -> ${relative(landing, page.out)}`);
}
