#!/usr/bin/env node
/**
 * build-legal.mjs — render the repository's legal documents into the landing.
 *
 * PRIVACY.md and TERMS.md at the repo root are the single source of truth.
 * This script renders them with `marked` and writes landing/privacy.html and
 * landing/terms.html, so the site can never drift from the repository: edit the
 * markdown, run `npm run dev` (or `npm run build`) and the pages follow.
 *
 * Output is deterministic — no build timestamp — so regenerating unchanged
 * documents produces no diff.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

import { marked } from 'marked';

const here = dirname(fileURLToPath(import.meta.url));
const landing = join(here, '..');
const repo = join(landing, '..');

const REPO_URL = 'https://github.com/mrsehajofficial/aegis/blob/main';

const PAGES = [
  {
    source: join(repo, 'PRIVACY.md'),
    out: join(landing, 'privacy.html'),
    title: 'Privacy Policy',
    badge: 'PRIVACY // DATA HANDLING',
    description:
      "How the Aegis Telegram bot handles data: what is stored, what never leaves the operator's host, and how to have data deleted.",
  },
  {
    source: join(repo, 'TERMS.md'),
    out: join(landing, 'terms.html'),
    title: 'Terms of Service',
    badge: 'TERMS // ACCEPTABLE USE',
    description:
      'The terms that apply to the Aegis Telegram bot: acceptable use, admin responsibilities, availability and liability.',
  },
];

const template = await readFile(join(landing, 'legal.template.html'), 'utf8');

for (const page of PAGES) {
  const markdown = await readFile(page.source, 'utf8');
  const content = await marked.parse(markdown, { gfm: true });
  const sourceFile = relative(repo, page.source);

  const html = template
    .replaceAll('{{TITLE}}', page.title)
    .replaceAll('{{BADGE}}', page.badge)
    .replaceAll('{{DESCRIPTION}}', page.description)
    .replaceAll('{{CONTENT}}', content)
    .replaceAll('{{SOURCE_FILE}}', sourceFile)
    .replaceAll('{{SOURCE_URL}}', `${REPO_URL}/${sourceFile}`)
    .replace(
      '<!-- generated -->',
      `<!-- GENERATED by scripts/build-legal.mjs from ${sourceFile}.\n` +
        '     Edit the markdown at the repository root, never this file. -->'
    );

  await writeFile(page.out, html, 'utf8');
  console.log(`legal: ${sourceFile} -> ${relative(landing, page.out)}`);
}
